restart_file: .na
start_datetime: 2020-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-01-01 00:00:00
forecast_horizon: 35.0
sim_name: bvre_DA_experiments_test
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: FALSE
